version: 2.1

jobs:
  build_and_test:
    docker:
      - image: circleci/python:3.7
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Check environment
          command: |
            python --version
            pip --version
            ls -la
      - run:
          name: Build and test
          command: |
            pip install poetry
            poetry install -v
            poetry run pytest

  version_check:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            pip install poetry
            poetry install
      - run:
          name: Semantic Release no-op
          command: |
            poetry run semantic-release version --noop -Dversion_source=${SEM_REL_VERSION_SOURCE} -Dversion_variable=${SEM_REL_VERSION_VARIABLE}

  release:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Build and test
          command: |
            pip install poetry
            poetry install
            poetry run pytest
      - add_ssh_keys:
          fingerprints:
            - "98:72:78:cf:4f:99:ac:99:8a:39:70:31:d7:ef:23:20"
      - run:
          name: Do legit release
          command: |
            git config --global user.email "${GH_USER_EMAIL}"
            git config --global user.name "${GH_USER}"
            cat .git/config
            
            echo ""
            echo "tags after before doing anything:"
            git tag --list
            
            # poetry run semantic-release version
            # note running this command alone seems to produce the tag (but we still need to push it)
            poetry run semantic-release version -Dversion_source=${SEM_REL_VERSION_SOURCE} -Dversion_variable=${SEM_REL_VERSION_VARIABLE}

            echo "python show version after semantic-release version command:"
            python semantic_release/__init__.py
            new_version=$(python semantic_release/__init__.py)
            
            if [[ $new_version == '0.0.0' ]]; then
                echo "new_version is default value"
                exit 0
            fi

            echo "version in pyproject.toml before updating:"
            poetry version  #show version

            poetry version $new_version

            echo "version in pyproject.toml after updating:"
            poetry version  #show version

            echo "tags before doing the build:"
            git tag --list

            echo "this is where to do the actual release"
            poetry build

            echo "tags after doing the build and before publish:"
            git tag --list

            # blocking publish for now till I sort out what's happening with the tags
            # poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD

            echo "tags after doing the publish:"
            git tag --list

            # git tag v${new_version}
            echo "trying to push a new tag:"
            echo "repo: ${CIRCLE_PROJECT_REPONAME}"
            # git push -q https://${GH_TOKEN}@github.com/${CIRCLE_PROJECT_REPONAME}.git v${new_version}
            git push origin v${new_version}

workflows:
  version: 2
  build_test_release:
    jobs:
      - build_and_test
      - version_check
      # - version_check:
          # context: undefined
          # filters:
          #   branches:
          #     only: master
      - release:
          # context: undefined
          requires:
            - version_check
            - build_and_test
          filters:
            branches:
              only: master
